services:
  - type: web
    name: koprip
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:server
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: SECRET_KEY
        generateValue: true
      - key: APP_PASSWORD
        sync: false
